apiVersion: v1
kind: Service
metadata:
  name: auction-service
  labels:
    app: auction-service
spec:
  type: ClusterIP
  selector:
    app: auction-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
