apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-service
  labels:
    app: settlement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement-service
  template:
    metadata:
      labels:
        app: settlement-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: settlement-service
          image: ghcr.io/prgrms-be-adv-devcourse/settlement:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8087
          env:
            - name: SERVER_PORT
              value: "8087"

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: EUREKA_HOST
              value: "discovery"

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: SPRING_DATASOURCE_DRIVER

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: JWT_SECRET

            - name: JWT_ACCESS_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: JWT_ACCESS_TOKEN_EXPIRATION

            - name: JWT_REFRESH_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: JWT_REFRESH_TOKEN_EXPIRATION

            - name: MORE_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: MORE_MAIL_USERNAME

            - name: MORE_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: MORE_MAIL_PASSWORD

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: KAFKA_BOOT_PORT
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: KAFKA_BOOT_PORT

            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: KAFKA_USER

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: KAFKA_PASSWORD

            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: ELASTIC_SEARCH_URL

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: REDIS_PORT

            - name: TOSS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: settlement-secret
                  key: TOSS_SECRET_KEY

            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx160m -XX:MaxMetaspaceSize=96m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 100
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
