apiVersion: v1
kind: Service
metadata:
  name: settlement-service
  labels:
    app: settlement-service
spec:
  type: ClusterIP
  selector:
    app: settlement-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087
