apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1 
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # 신규 Pod 동시에 추가하지 않음 → 최초 배포 1개만
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-1
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notification-service
          image: ghcr.io/prgrms-be-adv-devcourse/notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8089
          env:
            - name: SERVER_PORT
              value: "8089"

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: EUREKA_HOST
              value: "discovery"

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_DATASOURCE_DRIVER

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: JWT_SECRET

            - name: JWT_ACCESS_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: JWT_ACCESS_TOKEN_EXPIRATION

            - name: JWT_REFRESH_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: JWT_REFRESH_TOKEN_EXPIRATION

            - name: MORE_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MORE_MAIL_USERNAME

            - name: MORE_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MORE_MAIL_PASSWORD

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: KAFKA_BOOT_PORT
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: KAFKA_BOOT_PORT

            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: KAFKA_USER

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: KAFKA_PASSWORD

            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: ELASTIC_SEARCH_URL

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: REDIS_PORT

            - name: TOSS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: TOSS_SECRET_KEY

            - name: JAVA_TOOL_OPTIONS
              value: >
                -Duser.timezone=Asia/Seoul
                -Xmx96m
                -XX:MaxMetaspaceSize=128m
                -XX:MaxDirectMemorySize=32m
                -XX:ReservedCodeCacheSize=24m
                 

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8089
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8089
            periodSeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
            
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "352Mi"

