spring:
  application:
    name: product-service
  profiles:
    active: ${env.SPRING_PROFILES_ACTIVE:local}
server:
  port: 8085

---
spring:
  config:
    activate:
      on-profile: local

    import:
      - optional:configserver:http://localhost:8888
      - optional:file:.env[.properties]

  ai:
    vectorstore:
      pgvector:
        schema-name: product
        table-name: product_embed
        dimensions: 1536
        id-type: TEXT
        initialize-schema: false

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:configserver:http://config:8888
