#spring:
#  application:
#    name: product-service
#  config:
#    import: "configserver:http://localhost:8888"
#server:
#  port: 8085


spring:
  profiles:
    active: ${env.SPRING_PROFILES_ACTIVE:local}
