#spring:
#  application:
#    name: product-service
#  config:
#    import: "configserver:http://localhost:8888"
#server:
#  port: 8085


spring:
  application:
    name: product
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: validate       # 스키마 변경 금지, 매핑 검증만 수행
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  config:
    import:
      - optional:file:.env[.properties]          # 모듈 루트에서 실행할 때
      - optional:file:./product/.env[.properties]  # 멀티모듈 루트에서 실행할 때

  cloud:
    config:
      enabled: false # 로컬개발용으로 config 서버 접속 끊음 --> 배포시 true
    discovery:
      enabled: false # 로컬개발용으로 discovery 서버 접속 끊음 --> 배포시 true


api:
  v1: /api/v1


springdoc:
  pageable:
    enabled: true
    page-parameter: page
    size-parameter: size
    sort-parameter: sort

