apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery # deployment 소스의 이름 (k8s에서는 deployment/discovery처럼 저장)
  labels:
    app: discovery # deployment 검색을 위해 붙는 태그(콘솔에서 kubectl get deployments -l app=discovery과 같은 검색 시 필요)
spec:
  replicas: 1 
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: discovery # discovery 라벨이 붙은 Pod(template.metadata.labels.app에 명시)만 관리한다는 선언
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # 신규 Pod 동시에 추가하지 않음 → 최초 배포 1개만
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: discovery # pod에 실제로 붙는 라벨
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-1
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: discovery
          image: ghcr.io/prgrms-be-adv-devcourse/discovery:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8761
          env:
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: discovery

            - name: JAVA_TOOL_OPTIONS
              value: >
                -Duser.timezone=Asia/Seoul
                -Xmx96m

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 80
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6

          resources:
            requests:
              cpu: "100m"
              memory: "192Mi"
            limits:
              cpu: "500m"
              memory: "320Mi"