jwt:
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  secret: ${JWT_SECRET}
spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    pool:
      enabled: true
      initial-size: 2
      max-size: 10
      validation-query: SELECT 1
      max-idle-time: 15m
      max-acquire-time: 5s
      max-create-connection-time: 5s

springdoc:
  swagger-ui:
    urls:
      - name: Auction
        url: /swagger/auction-service
      - name: Notification
        url: /swagger/notification-service
      - name: Deposit
        url: /swagger/deposit-service
      - name: Product
        url: /swagger/product-service
      - name: Search
        url: /swagger/search-service
      - name: Settlement
        url: /swagger/settlement-service
      - name: User
        url: /swagger/user-service
      - name: File
        url: /swagger/file-service