spring:
  servlet:
    multipart:
      max-file-size: 20MB     # 파일 하나의 최대 용량
      max-request-size: 20MB  # 요청 전체(max-file-size 여러 개 합친 값)

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:team5-dev-high-bucket}
    region: ${AWS_REGION:ap-northeast-2}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}