spring:
  elasticsearch:
    uris: ${ELASTIC_SEARCH_URL}
    connection-timeout: 5s
    socket-timeout: 10s
  ai:
    openai:
      api-key: ${GPT_API_KEY}
      base-url: https://api.openai.com/
      chat:
        options:
          model: gpt-4.1
          temperature: 0.2
          max_completion_tokens: 768