spring:
  application:
    name: order-service
  config:
    import: "configserver:http://localhost:8888"

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_ADDRESS}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA}&options=-c%20TimeZone=Asia/Seoul
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: validate # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  batch:
    jdbc:
      initialize-schema: never


server:
  port: ${SERVER_PORT}

charge:
  amount: 30
