apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-1
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: file-service
          image: ghcr.io/prgrms-be-adv-devcourse/file-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9027
          env:
            - name: SERVER_PORT
              value: "9027"

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: EUREKA_HOST
              value: "discovery"

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: SPRING_DATASOURCE_DRIVER

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: JWT_SECRET

            - name: JWT_ACCESS_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: JWT_ACCESS_TOKEN_EXPIRATION

            - name: JWT_REFRESH_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: JWT_REFRESH_TOKEN_EXPIRATION

            - name: MORE_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: MORE_MAIL_USERNAME

            - name: MORE_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: MORE_MAIL_PASSWORD

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: KAFKA_BOOT_PORT
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: KAFKA_BOOT_PORT

            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: KAFKA_USER

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: KAFKA_PASSWORD

            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: ELASTIC_SEARCH_URL

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: REDIS_PORT

            - name: TOSS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: TOSS_SECRET_KEY

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-service-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: JAVA_TOOL_OPTIONS
              value: "-Duser.timezone=Asia/Seoul"
#              value: >
#                -Xms128m
#                -Xmx256m
#                -XX:MaxMetaspaceSize=128m

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9027
            initialDelaySeconds: 200
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9027
            initialDelaySeconds: 210
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources: {}
