#spring:
#  application:
#    name: file-service
#  config:
#    import: "configserver:http://localhost:8888"
#server:
#  port: 8085

spring:
  application:
    name: file-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  config:
    import:
      - optional:file:.env[.properties]          # 모듈 루트에서 실행할 때
      - optional:file:./file-service/.env[.properties]  # 멀티모듈 루트에서 실행할 때
  cloud:
    config:
      enabled: false # 로컬개발용으로 config 서버 접속 끊음 --> 배포시 true
    discovery:
      enabled: false # 로컬개발용으로 discovery 서버 접속 끊음 --> 배포시 true
aws:
  s3:
    bucket: ${AWS_S3_BUCKET:team5-dev-high-bucket}
    region: ${AWS_REGION:ap-northeast-2}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}



