apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  replicas: 1 
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # 신규 Pod 동시에 추가하지 않음 → 최초 배포 1개만
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: config
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-1
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: config
          image: ghcr.io/prgrms-be-adv-devcourse/config:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "git"

            - name: EUREKA_HOST
              value: "discovery"

            - name: CONFIG_GIT_URI
              value: "https://github.com/prgrms-be-adv-devcourse/beadv2_2_dev_high_BE" # 배포용 설정 리포 주소로 교체

            - name: CONFIG_GIT_LABEL
              value: "config"

            - name: CONFIG_GIT_SEARCH_PATHS
              value: "."

            - name: JAVA_TOOL_OPTIONS
              value: >
                -Duser.timezone=Asia/Seoul
                -Xmx96m           
                -XX:MaxMetaspaceSize=64m
                -XX:MaxDirectMemorySize=32m
                -XX:ReservedCodeCacheSize=16m
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            periodSeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
