apiVersion: v1
kind: Service
metadata:
  name: deposit-service
  labels:
    app: deposit-service
spec:
  type: ClusterIP
  selector:
    app: deposit-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
