spring:
  application:
    name: settlement-service
  config:
    import: "configserver:http://localhost:8888"

  # Database
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: validate # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: ${SPRING_DATABASE_PLATFORM}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  batch:
    jdbc:
      initialize-schema: never
    job:
      myJob:
        reader:
          pageSize: 1000 # Example page size

  task:
    scheduling:
      pool:
        size: 5


server:
  port: ${SERVER_PORT}
