apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: ghcr.io/prgrms-be-adv-devcourse/product:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: apigateway-secret
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER
              valueFrom:
                secretKeyRef:
                  name: apigateway-secret
                  key: SPRING_DATASOURCE_DRIVER

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apigateway-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: JWT_SECRET

            - name: JWT_ACCESS_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: JWT_ACCESS_TOKEN_EXPIRATION

            - name: JWT_REFRESH_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: JWT_REFRESH_TOKEN_EXPIRATION

            - name: MORE_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: MORE_MAIL_USERNAME

            - name: MORE_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: MORE_MAIL_PASSWORD

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: KAFKA_BOOT_PORT
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: KAFKA_BOOT_PORT

            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: KAFKA_USER

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: KAFKA_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 100
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"