spring:
  application:
    name: search-service
  profiles:
    active: ${env.SPRING_PROFILES_ACTIVE:local}
server:
  port: 8086

---
spring:
  config:
    activate:
      on-profile: local

    import:
      - optional:configserver:http://localhost:8888
      - optional:file:.env[.properties]

  ai:
    openai:
      api-key: ${GPT_API_KEY}
      base-url: https://api.openai.com/
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
          max_completion_tokens: 768

---
spring:
  config:
    activate:
      on-profile: prod
    import: "configserver:http://config:8888"
